"use client";

import Link from "next/link";
import { AlertTriangle, Bell, CheckCircle2, ChevronRight, CircleDot, FileText, LayoutDashboard, Menu, PackageSearch, Settings, Truck, Users, Zap } from "lucide-react";
import type { AutomationRule, AutomationRuleSeverity } from "@/lib/automation-rules";

export function AutomationRules({ rules }: { rules: AutomationRule[] }) {
  return <Shell active="Automation rules"><main className="mx-auto max-w-[1500px] px-4 py-6 lg:px-8 lg:py-8">
    <div className="mb-7 flex flex-wrap items-end justify-between gap-4"><div><p className="mb-2 text-[10px] font-semibold uppercase tracking-[0.24em] text-cyan-400">Settings / controlled automation</p><h1 className="text-2xl font-semibold tracking-tight text-white lg:text-3xl">Automation rules</h1><p className="mt-2 text-sm text-slate-500">Explicit operating logic that teams can inspect, explain, and audit.</p></div><span className="flex items-center gap-2 rounded border border-emerald-400/20 bg-emerald-400/[0.06] px-3 py-2 text-[10px] uppercase tracking-wider text-emerald-300"><CheckCircle2 size={13} /> {rules.filter((rule) => rule.enabled).length} active rules</span></div>
    <section className="mb-6 grid gap-3 sm:grid-cols-3"><Metric label="Rules in catalog" value={rules.length} detail="versioned domain definitions" /><Metric label="Categories" value={new Set(rules.map((rule) => rule.category)).size} detail="tracking, appointments, customer, docs, carrier" /><Metric label="Human escalation paths" value={rules.filter((rule) => rule.escalation !== "No escalation unless shipment is at risk").length} detail="not silent automation" tone="amber" /></section>
    <section className="overflow-hidden rounded border border-white/10 bg-[#11161c]"><div className="border-b border-white/10 px-5 py-4"><h2 className="text-sm font-semibold text-white">Rule catalog</h2><p className="mt-1 text-xs text-slate-500">Rules are read-only in this demo. The typed catalog is structured for later versioning and editing.</p></div><div className="divide-y divide-white/[0.07]">{rules.map((rule) => <article key={rule.id} className="grid gap-4 px-5 py-5 lg:grid-cols-[220px_minmax(250px,1.1fr)_120px_minmax(180px,1fr)_minmax(200px,1fr)] lg:items-start"><div><div className="flex items-center gap-2"><span className={`h-2 w-2 rounded-full ${rule.enabled ? "bg-emerald-400" : "bg-slate-600"}`} /><p className="text-xs font-semibold text-white">{rule.name}</p></div><p className="mt-2 font-mono text-[10px] text-slate-600">{rule.id}</p><span className="mt-2 inline-block rounded border border-white/10 px-2 py-1 text-[9px] uppercase tracking-wider text-slate-500">{rule.category}</span></div><div><p className="text-[9px] uppercase tracking-wider text-slate-600">Trigger</p><p className="mt-2 text-xs leading-5 text-slate-300">{rule.trigger}</p></div><div><p className="text-[9px] uppercase tracking-wider text-slate-600">Severity</p><span className={`mt-2 inline-block rounded border px-2 py-1 text-[9px] font-semibold uppercase tracking-wider ${severityClass(rule.severity)}`}>{rule.severity}</span></div><div><p className="text-[9px] uppercase tracking-wider text-slate-600">Action</p><p className="mt-2 text-xs leading-5 text-cyan-300">{rule.action}</p></div><div><p className="text-[9px] uppercase tracking-wider text-slate-600">Escalation</p><p className="mt-2 text-xs leading-5 text-slate-400">{rule.escalation}</p></div></article>)}</div></section>
    <section className="mt-6 grid gap-6 lg:grid-cols-2"><div className="rounded border border-cyan-400/20 bg-cyan-400/[0.04] p-5"><div className="flex gap-3"><Zap size={17} className="mt-0.5 text-cyan-300" /><div><h2 className="text-sm font-semibold text-white">Controlled by operations</h2><p className="mt-2 text-xs leading-5 text-slate-400">The engine uses explicit thresholds and domain fields. It does not infer intent, hide a confidence score, or make an unreviewable decision.</p></div></div></div><div className="rounded border border-white/10 bg-[#11161c] p-5"><h2 className="text-sm font-semibold text-white">Architecture note</h2><p className="mt-2 text-xs leading-5 text-slate-500">Each rule has a stable ID, typed severity, trigger, action, escalation, category, and enabled state. A future editor can add versions and approvals without moving logic into UI components.</p></div></section>
  </main></Shell>;
}

function severityClass(severity: AutomationRuleSeverity) { return severity === "critical" ? "border-red-400/30 bg-red-400/10 text-red-300" : severity === "warning" ? "border-orange-400/30 bg-orange-400/10 text-orange-300" : "border-sky-400/30 bg-sky-400/10 text-sky-200"; }
function Metric({ label, value, detail, tone = "cyan" }: { label: string; value: number; detail: string; tone?: "cyan" | "amber" }) { return <div className="rounded border border-white/10 bg-[#11161c] p-4"><p className={`text-[10px] uppercase tracking-wider ${tone === "amber" ? "text-amber-200" : "text-cyan-300"}`}>{label}</p><p className="mt-2 text-2xl font-semibold text-white">{value}</p><p className="mt-1 text-xs text-slate-600">{detail}</p></div>; }

const nav = [["Control Tower", LayoutDashboard, "/"], ["My Queue", Zap, "/my-queue"], ["Loads", PackageSearch, "#"], ["Exceptions", AlertTriangle, "#"], ["Carriers", Truck, "/carriers"], ["Documents", FileText, "/documents"], ["Customer updates", Users, "/customer-updates"], ["Analytics", CircleDot, "/analytics"], ["Automation rules", Settings, "/settings/automation-rules"]] as const;
function Shell({ active, children }: { active: string; children: React.ReactNode }) { return <div className="min-h-screen bg-[#0b0e12] text-slate-100"><aside className="fixed inset-y-0 left-0 z-30 hidden w-64 flex-col border-r border-white/10 bg-[#101419] lg:flex"><div className="flex h-20 items-center border-b border-white/10 px-5"><div className="flex items-center gap-2 text-sm font-semibold tracking-[0.2em] text-white"><span className="grid h-7 w-7 place-items-center rounded bg-cyan-400 text-[#071014]"><Zap size={15} fill="currentColor" /></span>FREIGHTFLOW</div></div><nav className="space-y-1 px-3 py-5">{nav.map(([label, Icon, href]) => <Link key={label} href={href} className={`flex items-center gap-3 rounded px-3 py-2.5 text-sm ${active === label ? "bg-cyan-400/10 text-cyan-300" : "text-slate-400 hover:bg-white/5"}`}><Icon size={17} /><span>{label}</span></Link>)}</nav><div className="mt-auto border-t border-white/10 p-4 text-xs text-slate-500">Maya Chen · Dispatcher</div></aside><div className="lg:pl-64"><header className="sticky top-0 z-20 flex h-20 items-center gap-3 border-b border-white/10 bg-[#0b0e12]/95 px-4 backdrop-blur lg:px-8"><button className="text-slate-400 lg:hidden" aria-label="Open navigation"><Menu size={20} /></button><div className="hidden items-center gap-2 text-xs text-slate-500 md:flex"><Link href="/">Control Tower</Link><ChevronRight size={13} /><span className="text-slate-200">{active}</span></div><div className="ml-auto"><Bell size={18} className="text-slate-400" /></div></header>{children}</div></div>; }
