"use client";

import Link from "next/link";
import { useMemo, useState } from "react";
import { AlertTriangle, Bell, Check, ChevronRight, CircleDot, FileText, LayoutDashboard, Menu, MessageSquare, PackageSearch, Send, Settings, Truck, UserCheck, Users, Zap } from "lucide-react";
import type { CommunicationEvent, Customer, Exception, Shipment } from "@/lib/domain";
import { customerProfiles, notificationEvents, previewMessage, updatesDue, type CommunicationMode, type NotificationChannel } from "@/lib/customer-comms";

export function CustomerCommunications({ communications, customers, exceptions, shipments }: { communications: CommunicationEvent[]; customers: Customer[]; exceptions: Exception[]; shipments: Shipment[] }) {
  const profiles = useMemo(() => customerProfiles(customers), [customers]);
  const due = useMemo(() => updatesDue(shipments, exceptions), [exceptions, shipments]);
  const [selectedId, setSelectedId] = useState(due[0]?.shipment.id ?? "");
  const [channel, setChannel] = useState<NotificationChannel>("email");
  const [mode, setMode] = useState<CommunicationMode>("automatic");
  const [customMessage, setCustomMessage] = useState("");
  const [sent, setSent] = useState<string | null>(null);
  const selected = due.find((item) => item.shipment.id === selectedId) ?? due[0];
  const message = selected ? previewMessage(selected, channel, customMessage) : "No customer update is currently due.";

  return <Shell active="Customer updates">
    <main className="mx-auto max-w-[1500px] px-4 py-6 lg:px-8 lg:py-8">
      <div className="mb-7 flex flex-wrap items-end justify-between gap-4"><div><p className="mb-2 text-[10px] font-semibold uppercase tracking-[0.24em] text-cyan-400">Customer communication layer</p><h1 className="text-2xl font-semibold tracking-tight text-white lg:text-3xl">Customer updates</h1><p className="mt-2 text-sm text-slate-500">Automate routine checkpoints. Keep service failures in human hands.</p></div><div className="flex items-center gap-2 text-xs text-slate-500"><span className="h-2 w-2 rounded-full bg-emerald-400" />{due.length} updates due</div></div>
      <section className="grid gap-3 sm:grid-cols-3"><Metric label="Updates due" value={due.length} detail="SLA checkpoints requiring work" tone="cyan" /><Metric label="Approval required" value={due.filter((item) => item.urgency === "approval required").length} detail="broker review before sending" tone="amber" /><Metric label="Critical escalations" value={due.filter((item) => item.urgency === "critical escalation").length} detail="broker + operations manager" tone="red" /></section>
      <section className="mt-6 grid gap-6 xl:grid-cols-[minmax(0,1fr)_420px]">
        <div className="space-y-6">
          <section className="rounded border border-white/10 bg-[#11161c]"><div className="border-b border-white/10 px-5 py-4"><h2 className="text-sm font-semibold text-white">Customer updates due</h2><p className="mt-1 text-xs text-slate-500">Routine updates send automatically; exceptions become reviewable drafts.</p></div><div className="divide-y divide-white/[0.07]">{due.map((item) => <button key={item.shipment.id} onClick={() => setSelectedId(item.shipment.id)} className={`grid w-full gap-3 px-5 py-4 text-left transition hover:bg-white/[0.03] lg:grid-cols-[minmax(180px,1fr)_minmax(160px,1fr)_auto] ${selected?.shipment.id === item.shipment.id ? "bg-cyan-400/[0.05]" : ""}`}><div><div className="flex flex-wrap items-center gap-2"><span className="font-mono text-sm font-semibold text-cyan-300">{item.shipment.loadNumber}</span><Urgency urgency={item.urgency} /></div><p className="mt-2 text-xs text-white">{item.shipment.customer.name}</p><p className="mt-1 text-[11px] text-slate-500">{item.shipment.origin} → {item.shipment.destination}</p></div><div><p className="text-[10px] uppercase tracking-wider text-slate-600">Why now</p><p className="mt-1 text-xs text-slate-300">{item.reason}</p><p className="mt-2 text-[10px] text-slate-600">Owner: {item.owner}</p></div><div className="flex items-center gap-2 self-center text-right text-[10px] text-slate-500"><span>{relative(item.dueAt)}</span><ChevronRight size={14} /></div></button>)}{!due.length && <div className="p-10 text-center text-xs text-slate-500">No customer updates are currently due.</div>}</div></section>
          <section className="rounded border border-white/10 bg-[#11161c]"><div className="border-b border-white/10 px-5 py-4"><h2 className="text-sm font-semibold text-white">Notification event catalog</h2><p className="mt-1 text-xs text-slate-500">Configurable triggers supported by the demo workflow.</p></div><div className="grid gap-2 p-5 sm:grid-cols-3">{notificationEvents.map((event, index) => <div key={event} className="flex items-center gap-2 rounded border border-white/[0.07] bg-white/[0.02] px-3 py-3 text-xs text-slate-300"><span className="font-mono text-[10px] text-cyan-300">{String(index + 1).padStart(2, "0")}</span>{event}</div>)}</div></section>
          <section className="rounded border border-white/10 bg-[#11161c]"><div className="border-b border-white/10 px-5 py-4"><h2 className="text-sm font-semibold text-white">Customer notification profiles</h2><p className="mt-1 text-xs text-slate-500">Preferences determine which routine events are sent automatically.</p></div><div className="divide-y divide-white/[0.07]">{profiles.map((profile) => <div key={profile.customer.id} className="flex flex-wrap items-center justify-between gap-3 px-5 py-3.5"><div><p className="text-xs font-medium text-white">{profile.customer.name}</p><p className="mt-1 text-[11px] text-slate-500">{profile.description}</p></div><div className="flex items-center gap-2">{profile.channels.map((item) => <span key={item} className="rounded border border-cyan-400/20 bg-cyan-400/[0.06] px-2 py-1 text-[9px] uppercase tracking-wider text-cyan-300">{item}</span>)}<span className="rounded border border-white/10 px-2 py-1 text-[9px] uppercase tracking-wider text-slate-500">{profile.preference.replaceAll("_", " ")}</span></div></div>)}</div></section>
        </div>
        <aside className="space-y-6">
          <section className="rounded border border-cyan-400/25 bg-cyan-400/[0.05] p-5"><div className="flex items-start gap-3"><MessageSquare size={18} className="mt-0.5 text-cyan-300" /><div><p className="text-[10px] uppercase tracking-wider text-cyan-300">Communication preview</p><h2 className="mt-2 text-lg font-semibold text-white">{selected?.shipment.loadNumber ?? "No due update"}</h2><p className="mt-1 text-xs text-slate-500">{selected?.shipment.customer.name ?? "Queue clear"}</p></div></div>{selected && <><div className="mt-5 grid grid-cols-3 gap-2"><Select label="Channel" value={channel} onChange={(value) => setChannel(value as NotificationChannel)} options={["email", "SMS", "portal"]} /><Select label="Mode" value={mode} onChange={(value) => setMode(value as CommunicationMode)} options={["automatic", "human-approved", "manually written"]} /></div><textarea value={customMessage} onChange={(event) => setCustomMessage(event.target.value)} placeholder="Leave blank to use the generated draft..." className="mt-4 min-h-28 w-full resize-y rounded border border-white/10 bg-[#0d1217] p-3 text-xs leading-5 text-slate-300 outline-none placeholder:text-slate-600 focus:border-cyan-400/40" /><div className="mt-3 rounded border border-white/10 bg-[#0d1217] p-4"><p className="text-[9px] uppercase tracking-wider text-slate-600">What the customer receives</p><p className="mt-2 text-xs leading-5 text-slate-300">{message}</p></div><div className="mt-4 flex items-center justify-between gap-3"><span className="flex items-center gap-2 text-[10px] text-slate-500">{mode === "automatic" ? <Zap size={13} className="text-cyan-300" /> : <UserCheck size={13} className="text-amber-300" />}{mode}</span><button onClick={() => setSent(`Preview ${channel} update queued for ${selected.shipment.loadNumber}`)} className="flex items-center gap-2 rounded bg-cyan-400 px-3 py-2 text-xs font-semibold text-[#071014] hover:bg-cyan-300"><Send size={14} /> {mode === "automatic" ? "Queue update" : "Submit for approval"}</button></div>{sent && <p className="mt-3 flex items-center gap-2 text-xs text-emerald-300"><Check size={14} />{sent}</p>}</>}</section>
          <section className="rounded border border-white/10 bg-[#11161c] p-5"><div className="flex items-start gap-3"><AlertTriangle size={16} className="mt-0.5 text-orange-300" /><div><h2 className="text-sm font-semibold text-white">Exception communication policy</h2><div className="mt-4 space-y-3 text-xs"><Policy label="Routine update" value="Automatic" tone="text-emerald-300" /><Policy label="Potential service failure" value="Draft + broker approval" tone="text-amber-200" /><Policy label="Critical service failure" value="Broker + operations manager" tone="text-red-300" /></div></div></div></section>
          <section className="rounded border border-white/10 bg-[#11161c] p-5"><h2 className="text-sm font-semibold text-white">Recent communication activity</h2><div className="mt-4 space-y-3">{communications.slice(0, 5).map((event) => <div key={event.id} className="flex gap-3 text-xs"><span className={`mt-1 h-2 w-2 shrink-0 rounded-full ${event.automated ? "bg-cyan-300" : "bg-amber-300"}`} /><div><p className="text-slate-300">{event.type.replaceAll("_", " ")} · {event.channel}</p><p className="mt-1 text-[10px] text-slate-600">{event.automated ? "Automatic" : "Human handled"} · {event.party}</p></div></div>)}</div></section>
        </aside>
      </section>
    </main>
  </Shell>;
}

function Select({ label, value, options, onChange }: { label: string; value: string; options: string[]; onChange: (value: string) => void }) { return <label className="col-span-1 text-[9px] uppercase tracking-wider text-slate-600">{label}<select value={value} onChange={(event) => onChange(event.target.value)} className="mt-1 w-full rounded border border-white/10 bg-[#0d1217] px-2 py-2 text-[10px] normal-case tracking-normal text-slate-300 outline-none">{options.map((option) => <option key={option}>{option}</option>)}</select></label>; }
function Policy({ label, value, tone }: { label: string; value: string; tone: string }) { return <div className="flex items-center justify-between gap-3 border-b border-white/[0.07] pb-2 last:border-0"><span className="text-slate-500">{label}</span><span className={tone}>{value}</span></div>; }
function Urgency({ urgency }: { urgency: "routine" | "approval required" | "critical escalation" }) { return <span className={`rounded border px-1.5 py-0.5 text-[9px] uppercase tracking-wider ${urgency === "critical escalation" ? "border-red-400/30 bg-red-400/10 text-red-300" : urgency === "approval required" ? "border-amber-300/30 bg-amber-300/10 text-amber-200" : "border-cyan-400/20 bg-cyan-400/10 text-cyan-300"}`}>{urgency}</span>; }
function Metric({ label, value, detail, tone }: { label: string; value: number; detail: string; tone: "cyan" | "amber" | "red" }) { return <div className="rounded border border-white/10 bg-[#11161c] p-4"><p className={`text-[10px] uppercase tracking-wider ${tone === "red" ? "text-red-300" : tone === "amber" ? "text-amber-200" : "text-cyan-300"}`}>{label}</p><p className="mt-2 text-2xl font-semibold text-white">{value}</p><p className="mt-1 text-xs text-slate-600">{detail}</p></div>; }
function relative(value: string) { const minutes = Math.round((Date.now() - new Date(value).getTime()) / 60000); return minutes < 0 ? `due in ${Math.max(1, Math.round(Math.abs(minutes) / 60))}h` : `${Math.max(1, Math.round(minutes / 60))}h overdue`; }

const nav = [["Control Tower", LayoutDashboard, "/"], ["My Queue", Zap, "/my-queue"], ["Loads", PackageSearch, "#"], ["Exceptions", AlertTriangle, "#"], ["Carriers", Truck, "/carriers"], ["Documents", FileText, "/documents"], ["Customer updates", Users, "/customer-updates"], ["Analytics", CircleDot, "#"], ["Settings", Settings, "#"]] as const;
function Shell({ active, children }: { active: string; children: React.ReactNode }) { return <div className="min-h-screen bg-[#0b0e12] text-slate-100"><aside className="fixed inset-y-0 left-0 z-30 hidden w-64 flex-col border-r border-white/10 bg-[#101419] lg:flex"><div className="flex h-20 items-center border-b border-white/10 px-5"><div className="flex items-center gap-2 text-sm font-semibold tracking-[0.2em] text-white"><span className="grid h-7 w-7 place-items-center rounded bg-cyan-400 text-[#071014]"><Zap size={15} fill="currentColor" /></span>FREIGHTFLOW</div></div><nav className="space-y-1 px-3 py-5">{nav.map(([label, Icon, href]) => <Link key={label} href={href} className={`flex items-center gap-3 rounded px-3 py-2.5 text-sm ${active === label ? "bg-cyan-400/10 text-cyan-300" : "text-slate-400 hover:bg-white/5"}`}><Icon size={17} /><span>{label}</span></Link>)}</nav><div className="mt-auto border-t border-white/10 p-4 text-xs text-slate-500">Maya Chen · Dispatcher</div></aside><div className="lg:pl-64"><header className="sticky top-0 z-20 flex h-20 items-center gap-3 border-b border-white/10 bg-[#0b0e12]/95 px-4 backdrop-blur lg:px-8"><button className="text-slate-400 lg:hidden" aria-label="Open navigation"><Menu size={20} /></button><div className="hidden items-center gap-2 text-xs text-slate-500 md:flex"><Link href="/">Control Tower</Link><ChevronRight size={13} /><span className="text-slate-200">{active}</span></div><div className="ml-auto"><Bell size={18} className="text-slate-400" /></div></header>{children}</div></div>; }
