"use client";

import Link from "next/link";
import { AlertTriangle, Bell, ChevronRight, CircleDot, FileText, LayoutDashboard, Menu, PackageSearch, Settings, Truck, Users, Zap } from "lucide-react";

type ExecutiveData = ReturnType<typeof import("@/lib/executive-metrics").executiveMetrics>;

export function ExecutiveCockpit({ data }: { data: ExecutiveData }) {
  return <Shell active="Executive cockpit"><main className="mx-auto max-w-[1500px] px-4 py-6 lg:px-8 lg:py-8">
    <div className="mb-7 flex flex-wrap items-end justify-between gap-4"><div><p className="mb-2 text-[10px] font-semibold uppercase tracking-[0.24em] text-cyan-400">Leadership view / operating control</p><h1 className="text-2xl font-semibold tracking-tight text-white lg:text-3xl">Executive cockpit</h1><p className="mt-2 text-sm text-slate-500">Is the operation under control, and where is pressure accumulating?</p></div><span className="flex items-center gap-2 text-xs text-slate-500"><span className="h-2 w-2 rounded-full bg-emerald-400" />Deterministic demo metrics</span></div>
    <section className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4 xl:grid-cols-8">{[["Active loads", data.today.active], ["Pickups remaining", data.today.pickups], ["Deliveries remaining", data.today.deliveries], ["Critical loads", data.today.critical], ["Customer escalations", data.today.escalations], ["Revenue in transit", currency(data.today.inTransitRevenue)], ["Revenue awaiting POD", currency(data.today.awaitingPod)], ["Billing ready", currency(data.today.billingReady)]].map(([label, value], index) => <div key={String(label)} className={`rounded border p-3.5 ${index === 3 || index === 4 ? "border-red-400/20 bg-red-400/[0.05]" : "border-white/10 bg-[#11161c]"}`}><p className="text-[9px] font-semibold uppercase tracking-[0.12em] text-slate-500">{label}</p><p className="mt-2 text-lg font-semibold text-white">{value}</p></div>)}</section>
    <section className="mt-6 grid gap-6 xl:grid-cols-[minmax(0,1fr)_380px]"><Panel title="Operational pressure" subtitle="Where management attention is needed today."><div className="grid gap-3 sm:grid-cols-2">{[["Critical exceptions", data.pressure.critical, "red"], ["High exceptions", data.pressure.high, "orange"], ["Average queue age", `${data.pressure.queueAge}h`, "amber"], ["Carrier response issues", data.pressure.carrierIssues, "orange"], ["Upcoming appointment risk", data.pressure.upcomingRisk, "red"]].map(([label, value, tone]) => <div key={String(label)} className="rounded border border-white/[0.07] bg-white/[0.02] p-4"><p className={`text-[10px] uppercase tracking-wider ${tone === "red" ? "text-red-300" : tone === "orange" ? "text-orange-300" : "text-amber-200"}`}>{label}</p><p className="mt-2 text-2xl font-semibold text-white">{value}</p></div>)}</div></Panel><Panel title="Dispatcher workload" subtitle="Unresolved exception ownership"><div className="space-y-3">{data.pressure.workload.slice(0, 5).map((row) => <div key={row.owner} className="flex items-center justify-between gap-3 text-xs"><span className="truncate text-slate-300">{row.owner}</span><span className="font-mono text-slate-200">{row.count}</span></div>)}</div></Panel></section>
    <section className="mt-6 grid gap-6 xl:grid-cols-2"><Panel title="System effectiveness" subtitle="Evidence that FreightFlow is reducing manual hunting, not replacing operator judgment."><div className="grid gap-3 sm:grid-cols-2">{[["Handled without manual intervention", `${data.effectiveness.handledWithoutManual}%`], ["Human interventions / 100 loads", data.effectiveness.interventionsPer100], ["Tracking automation coverage", `${data.effectiveness.trackingCoverage}%`], ["Automated customer updates", data.effectiveness.automatedUpdates], ["Avg exception resolution", `${data.effectiveness.resolutionHours}h modeled`]].map(([label, value]) => <MetricLine key={String(label)} label={String(label)} value={value} />)}</div></Panel><Panel title="Bottlenecks" subtitle="Derived statements from the current demo dataset."><div className="space-y-3">{data.bottlenecks.map((statement) => <div key={statement} className="flex gap-3 rounded border border-orange-400/15 bg-orange-400/[0.04] p-3 text-xs leading-5 text-slate-300"><AlertTriangle size={14} className="mt-1 shrink-0 text-orange-300" />{statement}</div>)}</div></Panel></section>
    <p className="mt-6 text-[10px] text-slate-600">Modeled values are derived from the fictional demo data and should be treated as operating signals, not financial claims.</p>
  </main></Shell>;
}

function Panel({ title, subtitle, children }: { title: string; subtitle: string; children: React.ReactNode }) { return <section className="rounded border border-white/10 bg-[#11161c] p-5"><h2 className="text-sm font-semibold text-white">{title}</h2><p className="mt-1 text-xs text-slate-500">{subtitle}</p><div className="mt-5">{children}</div></section>; }
function MetricLine({ label, value }: { label: string; value: string | number }) { return <div className="flex items-center justify-between border-b border-white/[0.07] pb-3 text-xs"><span className="text-slate-500">{label}</span><span className="font-mono text-slate-200">{value}</span></div>; }
function currency(value: number) { return `$${value.toLocaleString("en-US", { maximumFractionDigits: 0 })}`; }

const nav = [["Control Tower", LayoutDashboard, "/"], ["My Queue", Zap, "/my-queue"], ["Executive cockpit", CircleDot, "/executive"], ["Loads", PackageSearch, "#"], ["Exceptions", AlertTriangle, "#"], ["Carriers", Truck, "/carriers"], ["Documents", FileText, "/documents"], ["Customer updates", Users, "/customer-updates"], ["Analytics", CircleDot, "/analytics"], ["Settings", Settings, "/settings/automation-rules"]] as const;
function Shell({ active, children }: { active: string; children: React.ReactNode }) { return <div className="min-h-screen bg-[#0b0e12] text-slate-100"><aside className="fixed inset-y-0 left-0 z-30 hidden w-64 flex-col border-r border-white/10 bg-[#101419] lg:flex"><div className="flex h-20 items-center border-b border-white/10 px-5"><div className="flex items-center gap-2 text-sm font-semibold tracking-[0.2em] text-white"><span className="grid h-7 w-7 place-items-center rounded bg-cyan-400 text-[#071014]"><Zap size={15} fill="currentColor" /></span>FREIGHTFLOW</div></div><nav className="space-y-1 px-3 py-5">{nav.map(([label, Icon, href]) => <Link key={label} href={href} className={`flex items-center gap-3 rounded px-3 py-2.5 text-sm ${active === label ? "bg-cyan-400/10 text-cyan-300" : "text-slate-400 hover:bg-white/5"}`}><Icon size={17} /><span>{label}</span></Link>)}</nav><div className="mt-auto border-t border-white/10 p-4 text-xs text-slate-500">Maya Chen · Dispatcher</div></aside><div className="lg:pl-64"><header className="sticky top-0 z-20 flex h-20 items-center gap-3 border-b border-white/10 bg-[#0b0e12]/95 px-4 backdrop-blur lg:px-8"><button className="text-slate-400 lg:hidden" aria-label="Open navigation"><Menu size={20} /></button><div className="hidden items-center gap-2 text-xs text-slate-500 md:flex"><Link href="/">Control Tower</Link><ChevronRight size={13} /><span className="text-slate-200">{active}</span></div><div className="ml-auto"><Bell size={18} className="text-slate-400" /></div></header>{children}</div></div>; }
