"use client";
import { MobileNavigation } from "@/components/mobile-navigation";
import { operationsAnalytics } from "@/lib/operations-analytics";
import { useDemoSession } from "@/components/demo-session";

import Link from "next/link";
import { useState } from "react";
import { AlertTriangle, Bell, ChevronRight, CircleDot, FileText, LayoutDashboard, PackageSearch, Settings, Truck, Users, Zap } from "lucide-react";

import { SystemBoundary } from "@/components/system-boundary";


export function OperationsAnalytics() {
  const shared = useDemoSession();
  const shipments = shared.shipments;
  const data = operationsAnalytics(shared.shipments, shared.exceptions, shared.communications, shared.documents, shared.carriers);
  const [selected, setSelected] = useState<string | null>(null);
  const affected = selected === "service" ? shipments.filter((shipment) => shipment.riskScore >= 65) : selected === "documents" ? shipments.filter((shipment) => shipment.podStatus === "missing") : selected ? shipments.filter((shipment) => `${shipment.origin} → ${shipment.destination}` === selected) : [];
  return <Shell active="Analytics"><main className="mx-auto max-w-[1500px] px-4 py-6 lg:px-8 lg:py-8"><SystemBoundary />
    <div className="mb-7 flex flex-wrap items-end justify-between gap-4"><div><p className="mb-2 text-[10px] font-semibold uppercase tracking-[0.24em] text-cyan-400">Operations intelligence</p><h1 className="text-2xl font-semibold tracking-tight text-white lg:text-3xl">Analytics</h1><p className="mt-2 text-sm text-slate-500">Every metric answers a work question. Select a friction signal to inspect affected loads.</p></div><span className="rounded border border-cyan-400/20 bg-cyan-400/[0.06] px-3 py-2 text-[10px] uppercase tracking-wider text-cyan-300">Demo model · auditable assumptions</span></div>
    <section className="grid gap-3 sm:grid-cols-2 xl:grid-cols-5"><Metric label="Total loads" value={data.loadHealth.total} question="How much freight is in scope?" /><Metric label="Human intervention" value={data.loadHealth.intervention} question="Where does work enter the queue?" tone="amber" /><Metric label="Exception-free" value={data.loadHealth.exceptionFree} question="What is moving without intervention?" tone="green" /><Metric label="Exception rate" value={`${data.loadHealth.exceptionRate}%`} question="How often does freight create work?" tone="red" /><Metric label="Avg exceptions / load" value={data.loadHealth.averageExceptions} question="How dense is the operational friction?" /></section>
    <section className="mt-6 grid gap-6 xl:grid-cols-2">
      <Panel title="Dispatch workload" subtitle="Are operators spending time on preventable follow-up?"><div className="grid gap-3 sm:grid-cols-2">{[["Carrier contacts / load", data.dispatch.contactsPerLoad], ["Interventions / load", data.dispatch.interventionsPerLoad], ["Avg resolution time", `${data.dispatch.resolutionHours}h`], ["Queue aging", `${data.dispatch.queueAging}h modeled`], ["Calls avoided by tracking", data.dispatch.callsAvoided]].map(([label, value]) => <MetricLine key={String(label)} label={String(label)} value={value} />)}</div><p className="mt-4 text-[10px] text-slate-600">Calls avoided is modeled at 35% of active loads with current tracking coverage.</p></Panel>
      <Panel title="Document flow" subtitle="Where is delivered revenue waiting on paperwork?"><div className="grid gap-3 sm:grid-cols-2">{[["Delivered → POD", `${data.documents.deliveredToPod}h`], ["Delivered → billing-ready", `${data.documents.deliveredToBilling}h`], ["Revenue blocked", currency(data.documents.blockedRevenue)], ["Documents overdue", data.documents.overdue]].map(([label, value]) => <MetricLine key={String(label)} label={String(label)} value={value} />)}</div><button onClick={() => setSelected("documents")} className="mt-4 text-[10px] text-cyan-300 hover:text-cyan-200">Inspect loads blocked by POD <ChevronRight size={12} className="inline" /></button></Panel>
    </section>
    <section className="mt-6 grid gap-6 xl:grid-cols-[minmax(0,1fr)_360px]">
      <Panel title="High-exception lanes" subtitle="Which lanes create the most human work?"><div className="space-y-4">{data.lanes.map((row) => <button key={row.lane} onClick={() => setSelected(row.lane)} className="w-full text-left"><div className="flex justify-between gap-3 text-xs"><span className="truncate text-slate-300">{row.lane}</span><span className="font-mono text-orange-300">{row.exceptions} exceptions</span></div><div className="mt-2 h-1.5 rounded-full bg-white/10"><div className="h-full rounded-full bg-orange-400" style={{ width: `${Math.min(100, row.exceptions * 18)}%` }} /></div><div className="mt-1 flex gap-3 text-[10px] text-slate-600"><span>{row.loads.length} loads</span><span>{row.late} late delivery</span><span>{row.tracking} tracking issues</span></div></button>)}</div></Panel>
      <Panel title="Financial impact" subtitle="Modeled exposure, not claimed savings."><div className="space-y-4"><MetricLine label="Revenue awaiting documentation" value={currency(data.documents.blockedRevenue)} /><MetricLine label="Loads at service risk" value={data.financial.serviceRisk} /><MetricLine label="Detention/accessorial exposure" value={currency(data.financial.accessorialExposure)} /><MetricLine label="Manual follow-up labor" value={`${data.financial.laborHours}h estimated`} /></div><button onClick={() => setSelected("service")} className="mt-5 text-[10px] text-cyan-300 hover:text-cyan-200">Inspect service-risk loads <ChevronRight size={12} className="inline" /></button></Panel>
    </section>
    <section className="mt-6 grid gap-6 xl:grid-cols-2"><Panel title="Carrier performance" subtitle="Which partner signals explain intervention?"><div className="space-y-3">{data.carrierRows.map((carrier) => <Link key={carrier.id} href={`/carriers/${carrier.id}`} className="grid grid-cols-2 sm:grid-cols-[minmax(150px,1fr)_repeat(4,auto)] items-center gap-3 rounded border border-white/[0.07] px-3 py-3 hover:bg-white/[0.03]"><span className="truncate text-xs text-white">{carrier.name}</span><span className="text-[10px] text-slate-500">{carrier.averageResponseTime}m response</span><span className="text-[10px] text-slate-500">{carrier.trackingCompliance}% track</span><span className="text-[10px] text-slate-500">{carrier.onTimeDeliveryRate}% delivery</span><span className="text-[10px] text-orange-300">{carrier.exceptionRate}% exceptions</span></Link>)}</div></Panel><Panel title="Customer operations" subtitle="Who requires communication effort?"><div className="space-y-3">{data.customerRows.slice(0, 6).map((row) => <div key={row.customer.id} className="grid grid-cols-2 sm:grid-cols-[minmax(140px,1fr)_repeat(3,auto)] items-center gap-3 border-b border-white/[0.07] pb-3 text-[10px]"><span className="truncate text-xs text-white">{row.customer.name}</span><span className="text-slate-500">{row.exceptions} exceptions</span><span className="text-slate-500">{row.manual} manual comms</span><span className="text-orange-300">{row.detention} detention</span></div>)}</div></Panel></section>
    {selected && <section className="mt-6 rounded border border-cyan-400/20 bg-cyan-400/[0.04] p-5"><div className="flex items-center justify-between"><div><p className="text-[10px] uppercase tracking-wider text-cyan-300">Drill-down</p><h2 className="mt-1 text-sm font-semibold text-white">{selected === "documents" ? "Loads blocked by documentation" : selected === "service" ? "Loads at service risk" : selected}</h2></div><button onClick={() => setSelected(null)} className="text-xs text-slate-500 hover:text-white">Clear</button></div><div className="mt-4 grid gap-2 sm:grid-cols-2 lg:grid-cols-4">{affected.slice(0, 12).map((shipment) => <Link key={shipment.id} href={`/loads/${shipment.id}`} className="rounded border border-white/10 bg-[#11161c] p-3 hover:border-cyan-400/30"><p className="font-mono text-xs text-cyan-300">{shipment.loadNumber}</p><p className="mt-1 truncate text-[10px] text-slate-400">{shipment.customer.name}</p><p className="mt-2 text-[10px] capitalize text-slate-600">{shipment.currentStatus.replaceAll("_", " ")}</p></Link>)}</div></section>}
  </main></Shell>;
}

function Panel({ title, subtitle, children }: { title: string; subtitle: string; children: React.ReactNode }) { return <section className="rounded border border-white/10 bg-[#11161c] p-5"><h2 className="text-sm font-semibold text-white">{title}</h2><p className="mt-1 text-xs text-slate-500">{subtitle}</p><div className="mt-5">{children}</div></section>; }
function Metric({ label, value, question, tone = "cyan" }: { label: string; value: number | string; question: string; tone?: "cyan" | "amber" | "green" | "red" }) { return <div className="rounded border border-white/10 bg-[#11161c] p-4"><p className={`text-[10px] uppercase tracking-wider ${tone === "red" ? "text-red-300" : tone === "amber" ? "text-amber-200" : tone === "green" ? "text-emerald-300" : "text-cyan-300"}`}>{label}</p><p className="mt-2 text-2xl font-semibold text-white">{value}</p><p className="mt-1 text-[10px] text-slate-600">{question}</p></div>; }
function MetricLine({ label, value }: { label: string; value: string | number }) { return <div className="flex items-center justify-between border-b border-white/[0.07] pb-2 text-xs"><span className="text-slate-500">{label}</span><span className="font-mono text-slate-200">{value}</span></div>; }
function currency(value: number) { return `$${value.toLocaleString("en-US", { maximumFractionDigits: 0 })}`; }

const nav = [["Control Tower", LayoutDashboard, "/"], ["My Queue", Zap, "/my-queue"], ["Loads", PackageSearch, "/loads"], ["Exceptions", AlertTriangle, "/my-queue"], ["Carriers", Truck, "/carriers"], ["Documents", FileText, "/documents"], ["Customer updates", Users, "/customer-updates"], ["Analytics", CircleDot, "/analytics"], ["Settings", Settings, "/settings/automation-rules"]] as const;
function Shell({ active, children }: { active: string; children: React.ReactNode }) { return <div className="min-h-screen bg-[#0b0e12] text-slate-100"><aside className="fixed inset-y-0 left-0 z-30 hidden w-64 flex-col border-r border-white/10 bg-[#101419] lg:flex"><div className="flex h-20 items-center border-b border-white/10 px-5"><div className="flex items-center gap-2 text-sm font-semibold tracking-[0.2em] text-white"><span className="grid h-7 w-7 place-items-center rounded bg-cyan-400 text-[#071014]"><Zap size={15} fill="currentColor" /></span>FREIGHTFLOW</div></div><nav className="space-y-1 px-3 py-5">{nav.map(([label, Icon, href]) => <Link key={label} href={href} className={`flex items-center gap-3 rounded px-3 py-2.5 text-sm ${active === label ? "bg-cyan-400/10 text-cyan-300" : "text-slate-400 hover:bg-white/5"}`}><Icon size={17} /><span>{label}</span></Link>)}</nav><div className="mt-auto border-t border-white/10 p-4 text-xs text-slate-500">Maya Chen · Dispatcher</div></aside><div className="lg:pl-64"><header className="sticky top-0 z-20 flex h-20 items-center gap-3 border-b border-white/10 bg-[#0b0e12]/95 px-4 backdrop-blur lg:px-8"><MobileNavigation /><div className="hidden items-center gap-2 text-xs text-slate-500 md:flex"><Link href="/">Control Tower</Link><ChevronRight size={13} /><span className="text-slate-200">{active}</span></div><div className="ml-auto"><Bell size={18} className="text-slate-400" /></div></header>{children}</div></div>; }
